[app]
	version = "v 0.1.0"
	title = "MapCloud Tiler"
[output]
	#can be mbtiles/file
	format ="file"
	#the output dir
	#directory ="D:\\SGDownload\\ChinaGrid\\china2\\"
	directory ="D:\\downloads\\map\\"
[task]
	#number of fetchers
	workers = 20
	#number of savers
	savepipe = 9
	#min request interval, a speed limit, unit millisecond
	timedelay = 20
	# 仅统计不下载
	calconly = false

[tm]
	#name for mbtiles
	name = "藻渡水库dem"
	#max and min level for mbtiles
	min = 18
	max = 18
	#can be pbf/png/jpg
	format = "png"
	#can be xyz/tm
	schema = "xyz"
	#the vector tiles metadata tilejson
	#json = "./geojson/rect.geojson"
	#url is the schema url of tiles
	# url = "https://api.mapbox.com/v4/mapbox.mapbox-streets-v8/{z}/{x}/{y}.vector.pbf?sku=1016gFniej06a&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA"
	# url = "https://api.mapbox.com/v4/mapbox.mapbox-terrain-v2/{z}/{x}/{y}.vector.pbf?sku=1016gFniej06a&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA"
	# url = "https://api.maptiler.com/tiles/v3/{z}/{x}/{y}.pbf?key=KDhMfHvorAFkFe64wlZb"
	# url = "http://mt0.google.com/vt/lyrs=s&x={x}&y={y}&z={z}"
	# url = "https://t0.tianditu.gov.cn/DataServer?T=vec_w&x={x}&y={y}&l={z}&tk=75f0434f240669f4a2df6359275146d2"
	# url = "https://t0.tianditu.gov.cn/DataServer?T=img_w&x={x}&y={y}&l={z}&tk=e1a6fe2b5ee3dda24d73ad3ee443e155"

	url = "https://api.mapbox.com/raster/v1/mapbox.mapbox-terrain-dem-v1/{z}/{x}/{y}.webp?sku=101fxqAeRbtqp&access_token=pk.eyJ1IjoibW9zaHVpeWFuZ3l1ZSIsImEiOiJjbWJxODhwcHQwMTYxMmpxdmdrbDVzOWZhIn0.93db9jdAM7yaiT6tAbdHeQ"
#lrs can set diff boundaries for diff levels
  [[lrs]]
  	min = 1
  	max = 8
  	# geojson = "./geojson/id_1.geojson"
	geojson ="D:\\downloads\\demRange.geojson"
